export const HOST_GET_SUCCESS = 'HOST_GET_SUCCESS';
export const HOST_GET_FAILED = 'HOST_GET_FAILED';
export const HOST_SEND_REQUEST_SUCCESS = 'HOST_SEND_REQUEST_SUCCESS';
export const HOST_SEND_REQUEST_FAILED = 'HOST_SEND_REQUEST_FAILED';
export const HOST_CREATE_SUCCESS = 'HOST_CREATE_SUCCESS';
export const HOST_CREATE_FAILED = 'HOST_CREATE_FAILED';
