export const REPORTER_GET_PENDING_REQUEST_SUCCESS = 'REPORTER_GET_PENDING_REQUEST_SUCCESS';
export const REPORTER_GET_PENDING_REQUEST_FAILED = 'REPORTER_GET_PENDING_REQUEST_FAILED';
export const REPORTER_ACCEPT_REQUEST_SUCCESS = 'REPORTER_ACCEPT_REQUEST_SUCCESS';
export const REPORTER_ACCEPT_REQUEST_FAILED = 'REPORTER_ACCEPT_REQUEST_FAILED';
export const REPORTER_REJECT_REQUEST_SUCCESS = 'REPORTER_REJECT_REQUEST_SUCCESS';
export const REPORTER_REJECT_REQUEST_FAILED = 'REPORTER_REJECT_REQUEST_FAILED';
