export const USER_DATA_POPULATE_HOST_SUCCESS = 'USER_DATA_POPULATE_HOST';
export const USER_DATA_POPULATE_USER_SUCCESS = 'USER_DATA_POPULATE_USER_SUCCESS';
export const USER_DATA_POPULATE_REPORTER_SUCCESS = 'USER_DATA_POPULATE_REPORTER_SUCCESS';
export const USER_DATA_POPULATE_REPORTER_ERROR = 'USER_DATA_POPULATE_REPORTER_ERROR';
export const USER_DATA_DESTROY = 'USER_DATA_DESTROY';
export const SET_ACTIVE_HOST = 'SET_ACTIVE_HOST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILED = 'USER_UPDATE_FAILED';
